### ISSUE TITLE
Opprydding

### ISSUE THREAD

**Issue by Ingerid** [Sprakbanken/sentimentanalyse#5]
- [x] Foreslår videre at beskrivelsen av kildekode og utdata kopieres inn i sentiment_analysis_timeseries fra README, slik at den blir et selvstendig dokument. 

- [x] Foreslår også at vi sletter gamle notebøker.

_Originally posted by @tungland in https://github.com/Sprakbanken/sentimentanalyse/pull/4#pullrequestreview-1234595435_

**Comment by tungland** [comment]
Done and done
